### ISSUE TITLE
Test newer Go versions

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix.v3#10]
Go is currently at version 1.10 but the .travis.yml still [tests only Go 1.8](https://github.com/mediocregopher/radix.v3/blob/9f9e105e072ae31c7d9fce1683a007dd72a95ebe/.travis.yml).

The Go team [supports only the current and previous versions](https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance), currently Go 1.0 and Go 1.9 (security only), so I propose to do the same and always support the last 2 versions.

**Comment by mediocregopher** [comment]
I'm down for that. My travis-foo isn't very good, do you know if there's macros or something where it can fill in the current and previous version automatically? Or does it have to be changed manually for each new go release?

**Comment by mediocregopher** [comment]
I'm down for that. My travis-foo isn't very good, do you know if there's macros or something where it can fill in the current and previous version automatically? Or does it have to be changed manually for each new go release?

**Comment by mediocregopher** [comment]
I'm down for that. My travis-foo isn't very good, do you know if there's macros or something where it can fill in the current and previous version automatically? Or does it have to be changed manually for each new go release?

**Comment by mediocregopher** [comment]
Alright well my phone just did something incredible, sorry about the triple post >_<

**Comment by nussjustin** [comment]
np :-)

Travis installs it's go versions with [gimme](https://github.com/travis-ci/gimme#gimme-). The available options are:

- 1.x 
- stable (current stable release, e.g. 1.10)
- tip (current master branch of [golang/go](https://github.com/golang/go))

So we could at least do "stable".

**Comment by mediocregopher** [comment]
I went ahead and enumerated 1.10 and 1.9, if we have to explicitly include 1.9 might as well be explicit about both.
