### ISSUE TITLE
Can't differentiate between GET with 0 or (nil) return value

### ISSUE THREAD

**Issue by solarfly73** [mediocregopher/radix.v3#15]
Hi! Really enjoying integrating radix in our API framework.  Sorry if this is a dumb question.

If a key does not exist, err will be nil, but (due to the int64 type below), the return value from the redis call is 0 (redis in fact will have returned nil):
```
    err := client.Do(radix.Cmd(&b, "EXISTS", key))
    fmt.Printf("Exists '%t' err is '%v'", b, err)

    var expires int64
    err = client.Do(radix.Cmd(&expires, "GET", key))
    if err != nil {
        fmt.Printf("GET %s failed", key)
        return false, 0, err
    }
```
The Redis spec allows for GET to return a (nil) special type in the case where a key doesn't exist. How does radix.v3 allow developers to detect the difference? Do I have to call  EXISTS along with GET inside a Pipeline?

**Comment by mediocregopher** [comment]
Hey @solarfly73 thanks for pointing this out. I definitely wouldn't want anyone to have to perform extra redis commands to satisfy the driver, that would be a reversal of priorities for sure. It would have been possible to do this before by mucking around in the `resp` package, but I'd rather not make people do that unless they're doing something really crazy, and checking for a nil response is pretty normal. So I implemented a new type in the main package, [MaybeNil](https://godoc.org/github.com/mediocregopher/radix.v3#MaybeNil) for you to use.

Thanks for trying out the package, and let me know if there's anything else you have trouble doing with it :)

**Comment by solarfly73** [comment]
Thanks!!
