### ISSUE TITLE
Documentation example for MULTI...EXEC

### ISSUE THREAD

**Issue by solarfly73** [mediocregopher/radix.v3#17]
I was hoping to get an example or two (and add it to the docs) for MULTI--EXEC and best practice.

I am using a WithConn block to try MULTI and EXEC. I'm wondering what the best approach is, since conn.Do could return an error at any point along the way?  If there's an error in the middle of a MULTI block and I returned with an error, wouldn't the MULTI never get rolled back (eg. say the Client runs out of pool connections or the system hits the file descriptor limit)?

contrived example:
```
poolOrClusterClient.Do(radix.WithConn(key, func(conn radix.Conn) error {
        var err error
        if err = conn.Do(radix.Cmd(nil, "MULTI")); err != nil {
            return err
        }
       var rc int
        if err = conn.Do(radix.Cmd(&rc, "EXISTS", key)); err == nil {
            if err := conn.Do(radix.Cmd(nil, "DEL", key)); err != nil {
                  // ???
            }
        }
        if err = conn.Do(radix.Cmd(nil, "EXEC")); err != nil {
            return err
        }
        return nil
}))
```

**Comment by mediocregopher** [comment]
I'm gonna go ahead and close this, if there's any more clarity which could be added to the docs feel free to reopen this and let me know.
