### ISSUE TITLE
*Pool.doRefill() creates redundant connections while doing commands

### ISSUE THREAD

**Issue by PROger4ever** [mediocregopher/radix.v3#18]
Radix.v3 creates new connections and closes them frequently because of some connections are taken temporally from pool to do commands.

**Example with interval ping:**
The scheme of the example: https://drive.google.com/file/d/1NczXcPK0k1FCqeHz6nZsB-2dBe3q5brZ/view?usp=sharing
1. _atIntervalDo()_ runs `sp.Do(Cmd(nil, "PING"))`;
2. In the same time (different goroutines):
    - _*Pool.Do()_ gets an connection and do the ping-command;
    - _atIntervalDo()_ runs `sp.doRefill()`;
3. _*Pool.doRefill()_ detects insufficiency of connections in the pool (1 conn is taken to ping);
4.  In the same time (different goroutines):
    - the ping-command ends, _*Pool.Do()_ returns the gotten connection to the pool (the pool is full again);
     - _*Pool.doRefill()_ creates new connection 'cause of point 3;
5. _*Pool.doRefill()_ tries to put the created connection from 4.2 to the pool, but it's full. It tries to put the connection to overflow. When the overflow is full too - it closes connections;
6. Repeat.

**How to reproduce:**
_main.go:_
```go
package main

import (
	"fmt"
	"log"
	"github.com/mediocregopher/radix.v3"
	"time"
	"strconv"
)

func redisConnSelectDb(db int) func(network, addr string) (radix.Conn, error) {
	dbStr := strconv.Itoa(db)
	return func(network, addr string) (radix.Conn, error) {
		conn, err := radix.DialTimeout(network, addr, 1*time.Minute)
		if err != nil {
			return nil, err
		}
		if err := conn.Do(radix.Cmd(nil, "SELECT", dbStr)); err != nil {
			conn.Close()
			return nil, err
		}
		return conn, nil
	}
}

func main() {
	conf, err := LoadConfig("config.json", "config-custom.json")
	if err != nil {
		log.Fatal(err)
	}

	redisAddress := fmt.Sprintf("%s:%d", conf.Redis.Host, conf.Redis.Port)
	pool0, err := radix.NewPool("tcp", redisAddress, 20, radix.PoolConnFunc(redisConnSelectDb(1)))
	if err != nil {
		log.Fatal(err)
	}

	for {
		fmt.Printf("1: %d\n", pool0.NumAvailConns() /*, pool1.NumAvailConns(), pool2.NumAvailConns()*/)
		time.Sleep(1 * time.Second)
	}
}
```
_pool.go (lines 362-379):_
```go
func (sp *Pool) put(spc *staticPoolConn) {
	sp.l.RLock()
	defer sp.l.RUnlock()
	if spc.lastIOErr != nil || sp.closed {
		spc.Close()
		return
	}

	select {
	case sp.pool <- spc:
	default:
		select {
		case sp.overflow <- spc:
		default:
			spc.Close()
			fmt.Print("a connection closed as redundant") //TODO: Remove after debug!!!!!!!!!!!!!!!!!
		}
	}
}
```
Run and wait some time for random synchronization.
**Please, fix it.**

**Comment by PROger4ever** [comment]
**Possible ways to fix it:**
1. Count the gotten connections;
2. Store gotten connections;
3. ???

**Comment by mediocregopher** [comment]
I see the issue you're referencing. Ultimately it's not _super_ pressing, the pool making and closing a redis connection every few seconds isn't really a huge deal for either the pool or redis, but you're right it's not ideal. I'll think about what the best way to solve it is.

**Comment by PROger4ever** [comment]
Let's imagine typical production situation. Your service have incoming requests non-stop/constantly. You set connection limit to 20 for the pool and 5 from them are used almost all the time.

**Comment by PROger4ever** [comment]
Let's imagine typical production situation. Your service have incoming requests non-stop/constantly. You set connection limit to 20 for the pool and at least 5 from them are usef almost all the time.
*Pool.doRefill() runs every second, check if the pool is not full and then creates a new connection.  **It does create a new connection every second.**

**Comment by PROger4ever** [comment]
Let's imagine typical production situation. Your service have incoming requests non-stop/constantly. You set connection limit to 20 for the pool and at least 5 from them are usef almost all the time.
*Pool.doRefill() runs every second, check if the pool is not full and then creates a new connection. The mission of any pool is to prevent creating new connections, but **it does create a new connection every second.**
It wastes resourses of the server for no reason. It's not acceptable for production
