### ISSUE TITLE
*Pool.doRefill()  isn't thread-safe but it should

### ISSUE THREAD

**Issue by PROger4ever** [mediocregopher/radix.v3#19]
**The code section:**
```go
func (sp *Pool) doRefill() {
	if len(sp.pool) == cap(sp.pool) {
		return
	}
	spc, err := sp.newConn()
	if err == nil {
		sp.put(spc)
	}
}
```
**The issue:**
After the check is passed, _sp.pool_ can be changed in other radix-goroutines (through _Do()_, _atIntervalDo()_). It can cause creating of redundant connections.
_len()_ and _cap()_ with channels - isn't the best idea. It's not acceptable for production :(
**Possible solutions:**
1. Replace channels with an collection (like queue, slice) and a mutex to lock it before the comparison.
Go channels aren't so good:
https://www.jtolio.com/2016/03/go-channels-are-bad-and-you-should-feel-bad/
https://medium.com/@robot_dreams/goroutines-and-channels-arent-free-a8684f3b6560
2. ???

**Comment by mediocregopher** [comment]
Hi @PROger4ever, your issues that you've submitted are pretty much identical, so I'm going to close this one and and focus on the other one. You're right that there is a potential creation of redundant connections, but protecting the `len(...) == cap(...)` section in a lock wouldn't solve it.

As for the links you posted, neither of those is particularly useful. The first is a specific case where someone was using channels in an IO-bound use-case, where they caused a slowdown. Connection Pool operations happen on a much slower scale than IO, so the overhead from each using a channel is negligible. As for the second link, tbh I didn't fully read it, but that person seems to be more pointing out cases where purely using go channels isn't the cleanest solution to a problem, which isn't really helpful here. Neither link should lead anyone to conclude that channels aren't ever good.
