### ISSUE TITLE
about hmset

### ISSUE THREAD

**Issue by cute-angelia** [mediocregopher/radix.v3#20]
```
// demo
type User struct {
    Id         int32  `json:"id"`
}
data := User{
    32, 
}  // 
m := structs.Map(data)

RedisPool.Do(radix.FlatCmd(nil, "HMSET", redisKey, m))


```

a problem :  Key in redis is uppercase

Is there a way to let redis's key lowercase ?

**Comment by mediocregopher** [comment]
Are you referring to the `Id` field being uppercase? That is something which is done by your `structs.Map` function when it's converting the struct to a map, it's not something radix has control of.
