### ISSUE TITLE
Frequent flushing with pipelines

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix.v3#27]
The implementation of [Pipeline](https://godoc.org/github.com/mediocregopher/radix.v3#Pipeline) [calls Encode for each command in the pipeline](https://github.com/mediocregopher/radix.v3/blob/c543119feea734570c988dc922d137ec14d0df91/action.go#L435-L447) which can be quiet slow.

The problem is that `connWrap.Encode` flushes the underlying `bufio.Writer` with each call. Calling `Flush` with each call is the right behavior in most cases, but can really hurt for pipelines. For one of my local tools the calls to `Flush` take up ~40% (1.8 seconds!) of the whole pipeline processing time.

I currently use a copy of `Pipeline`/`pipeline` that implements the `resp.Marshaler` interface and `Encode`s itself, like this:

```go
func (p pipeline) Run(c radix.Conn) error {
	if err := c.Encode(p); err != nil {
		return err
	}
	for _, cmd := range p {
		if err := c.Decode(cmd); err != nil {
			return err
		}
	}
	return nil
}

func (p pipeline) MarshalRESP(w io.Writer) error {
	for _, cmd := range p {
		if err := cmd.MarshalRESP(w); err != nil {
			return err
		}
	}

	return nil
}
```

This way we only need 1 manual call to `Flush`, making use of the internal flushing of the underlying `bufio.Writer` for larger pipelines.

@mediocregopher Any opinions on this approach?

**Comment by mediocregopher** [comment]
That seems fine to me, if you wanna submit a PR I'll merge it. If you could include a comment on MarshalRESP explaining why it's there that'd be helpful for the future.
