### ISSUE TITLE
Redigo benchmarks are whack

### ISSUE THREAD

**Issue by mediocregopher** [mediocregopher/radix.v3#29]
```
goos: linux
goarch: arm
pkg: github.com/mediocregopher/radix.v3
...
BenchmarkSerialGetSet/radix-4      10000            493083 ns/op              99 B/op          6 allocs/op
BenchmarkSerialGetSet/redigo-4      5000            208302 ns/op              46 B/op          5 allocs/op
BenchmarkParallelGetSet/radix-4                      100          20659156 ns/op            5179 B/op         26 allocs/op
BenchmarkParallelGetSet/redigo-4                   20000             60535 ns/op              63 B/op          6 allocs/op
```

I'm not _super_ concerned about the serial ones, but the parallel case (Pool) definitely needs to be improved. I don't know where all those extra allocs came from, possibly 7b5d070.

**Comment by nussjustin** [comment]
There are a few problems with the benchmarks and the pool performance.

The benchmarks currently use custom logic for parallel testing, which can confuse `go test`. Instead the tests should use `B.RunParallel` and `b.SetParallelism`. Also having too many goroutines negatively affects performance as well. It's probably better to start testing with a parallelism of GOMAXPROCS and then increasing to GOMAXPROCS*2, GOMAXPROCS*4, etc.

The get method of the Pool is quite allocation heavy. The code could easily be simplified and changed to avoid most allocations. The other allocations come mostly from the Cmd's themselfs.

I've just pushed a [parallel-performance](https://github.com/nussjustin/radix.v3/tree/parallel-performance) branch to my fork ([diff here](https://github.com/mediocregopher/radix.v3/compare/master...nussjustin:parallel-performance?expand=1)) that removes the custom benchmark logic and optimizes the pool allocations.

On my machine, the parallel-performance branch gives me the following:

```
go test -bench GetSet -benchmem -run ^$
goos: linux
goarch: amd64
pkg: github.com/mediocregopher/radix.v3
BenchmarkSerialGetSet/radix-8              30000             40239 ns/op             195 B/op          6 allocs/op
BenchmarkSerialGetSet/redigo-8             50000             39528 ns/op              86 B/op          5 allocs/op
BenchmarkParallelGetSet/radix-8           100000             13034 ns/op             229 B/op          7 allocs/op
BenchmarkParallelGetSet/redigo-8          100000             11596 ns/op             123 B/op          6 allocs/op
PASS
ok      github.com/mediocregopher/radix.v3      6.705s
```

**Comment by mediocregopher** [comment]
I made a branch, cmdActionPool, where I managed to shave 2 allocations per benchmark iteration by making a Pool for cmdActions (and consolidated the flatCmdAction into that type in the process).

My benchmarks in that branch are now inconsistent as to whether radix is faster in the benchmarks than redigo, and I can't test the parallel benches at all >_<

```
 ~/src/go/src/github.com/mediocregopher/radix.v3 ⎇ cmdActionPool ☉ ▻ go test -v -run=XXX -bench=BenchmarkSerialGetSet -benchmem -memprofilerate=1 -benchtime 20s
goos: linux                                                                                                                         
goarch: arm64                                                                                      
pkg: github.com/mediocregopher/radix.v3                                                                                                                         
BenchmarkSerialGetSet/radix-4             100000            270369 ns/op              67 B/op          4 allocs/op                                              
BenchmarkSerialGetSet/redigo-4             50000            431062 ns/op              86 B/op          5 allocs/op                  
PASS                                                                                               
ok      github.com/mediocregopher/radix.v3      58.483s                                                                                                         
 ~/src/go/src/github.com/mediocregopher/radix.v3 ⎇ cmdActionPool ☉ ▻ go test -v -run=XXX -bench=BenchmarkSerialGetSet -benchmem -memprofilerate=1 -benchtime 30s
goos: linux                                                                                                                         
goarch: arm64                                                        
pkg: github.com/mediocregopher/radix.v3                                                                                                                         
BenchmarkSerialGetSet/radix-4             300000            350987 ns/op              67 B/op          4 allocs/op                                              
BenchmarkSerialGetSet/redigo-4            200000            349842 ns/op              86 B/op          5 allocs/op
PASS                                                       
ok      github.com/mediocregopher/radix.v3      199.339s
```

**Comment by nussjustin** [comment]
In your bench runs you are using `-memprofilerate=1`, which shouldn't be used for direct comparisons as it samples every allocation and is far of from the default value (512*1024). Try to benchmark with the default rate and use `-count` (e.g. `-count 10`, higher numbers are better). Then you can use rsc.io/benchstat to get a more stable result.
