### ISSUE TITLE
Pool could provider more connections more than pool size

### ISSUE THREAD

**Issue by hotdust** [mediocregopher/radix.v3#3]
Following source is get method of pool.go.
According to "default: return sp.newConn()",  Does it mean if there is no sufficient connection in pool channel, it will temporarily create new connection. The connections that can be use, are more than pool size specified.

> pool.go
```
func (sp *Pool) get() (*staticPoolConn, error) {
	sp.l.RLock()
	defer sp.l.RUnlock()
	if sp.closed {
		return nil, errClientClosed
	}

	select {
	case spc := <-sp.pool:
		return spc, nil
	default:
		return sp.newConn()
	}
}
```

**Comment by mediocregopher** [comment]
That is correct. If there's a spike in load and all the connections in the
pool are used then new ones will be temporarily created. You can think of
the pool size as the maximum number of idle connections.

**Comment by hotdust** [comment]
thank you for your reply

**Comment by PROger4ever** [comment]
@mediocregopher 
Isn't it better to implement the pool in the common way: limit total connections number, getting connection with timeout (through context)? As do redigo and all nonredis pools to prevent connections overflow?
