### ISSUE TITLE
Avoid WithConn when possible with Redis Cluster

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix.v3#32]
Calling `Do` on a `*Cluster` currently always wraps the `Action` with `WithConn`.

https://github.com/mediocregopher/radix.v3/blob/6501e39a206c4e65228f6a05aac97d1fdd66d1ef/cluster.go#L332-L345

From my understanding of the code and the Redis Cluster protocol, the `WithConn` is only necessary when also sending the `ASKING` command. That means for most calls the `WithConn` does basically nothing and can be skipped unless `ask == true`.

Although calling `WithConn` does not hurt correctness, it still hurts allocations quite a bit, which can be seen when changing `doInner` to only call `WithConn` when `ask == true`.

Since I'm not that familiar with the Redis Cluster protocol / logic I wanted to double check that my understanding here is correct, before making a change.

Here's a diff that makes the `WithConn` call optional and adds a benchmark for the `Cluster.Do` implementation. 

```diff
diff --git a/cluster.go b/cluster.go
index 4fb8c08..1a93f8e 100644
--- a/cluster.go
+++ b/cluster.go
@@ -323,14 +323,17 @@ func (c *Cluster) doInner(a Action, addr, key string, ask bool, attempts int) er
                return err
        }
 
-       err = p.Do(WithConn(key, func(conn Conn) error {
-               if ask {
+       if ask {
+               err = p.Do(WithConn(key, func(conn Conn) error {
                        if err := conn.Do(Cmd(nil, "ASKING")); err != nil {
                                return err
                        }
-               }
-               return conn.Do(a)
-       }))
+
+                       return conn.Do(a)
+               }))
+       } else {
+               err = p.Do(a)
+       }
 
        if err == nil {
                return nil
diff --git a/cluster_test.go b/cluster_test.go
index 6c84ffe..94365c5 100644
--- a/cluster_test.go
+++ b/cluster_test.go
@@ -136,6 +136,19 @@ func TestClusterDo(t *T) {
        }
 }
 
+func BenchmarkClusterDo(b *B) {
+       c, _ := newTestCluster()
+
+       k, v := clusterSlotKeys[0], randStr()
+       require.Nil(b, c.Do(Cmd(nil, "SET", k, v)))
+
+       b.ResetTimer()
+
+       for i := 0; i < b.N; i++ {
+               require.Nil(b, c.Do(Cmd(nil, "GET", k)))
+       }
+}
+
 func TestClusterWithPrimaries(t *T) {
        c, _ := newTestCluster()
        var topo ClusterTopo
```

Benchmark results with (`benchstat`):

```
name         old time/op    new time/op    delta
ClusterDo-8    5.59µs ± 1%    5.60µs ± 3%     ~     (p=0.434 n=9+10)

name         old alloc/op   new alloc/op   delta
ClusterDo-8    4.85kB ± 0%    4.78kB ± 0%   -1.37%  (p=0.000 n=9+9)

name         old allocs/op  new allocs/op  delta
ClusterDo-8      20.0 ± 0%      17.0 ± 0%  -15.00%  (p=0.000 n=10+10)
```

Using a real Redis Cluster the allocation difference is the same (the total number of allocations is much lower in both cases, but there are still 3 allocations saved).

**Comment by mediocregopher** [comment]
Yup, that seems right to me. If you wanna submit a PR for it that'd be awesome, only thing I'd ask is to add a comment at the new `if` statement explaining that it's differentiated for performance reasons.
