### ISSUE TITLE
can't connection redis-cluster 

### ISSUE THREAD

**Issue by rubinus** [mediocregopher/radix.v3#40]
the problem is :

192.168.30.70  is a ip on the physical machine

the virtual machine ip is 10.20.80.132  on the 192.168.30.70

one:
i use the 10.20.80.132 install docker,and the redis-cluster on the docker use the --net=host

two:
i use the 10.20.80.132 install redis cluster not use the docker

one and two both not connection
error connecting to 192.168.30.70:7000: dial tcp 192.168.30.70:7000: i/o timeout

**Comment by mediocregopher** [comment]
@rubinus did you get this resolved? If not, can you explain what setup you're trying to get? I'm having trouble understanding.

It sounds like you have a virtual machine (not docker) running on an EC2 instance? If so, can you make sure whatever port redis is running on is being forwarded from the physical machine into the VM?

**Comment by mediocregopher** [comment]
@rubinus I'm gonna go ahead and close this, feel free to reopen it if you're still having issues.
