### ISSUE TITLE
Are pipelines supported in cluster mode?

### ISSUE THREAD

**Issue by varknull** [mediocregopher/radix.v3#45]
Hello there,

are pipelines supported in cluster mode?

Cheers,
V

**Comment by nussjustin** [comment]
radix.v3 supports pipelines with Redis Cluster as long as **all** keys in the pipeline are part of the same cluster slot. In practice this means only a single key or keys with explicit hash tags (e.g. `a{b}c` and `d{b}f`) can be used. The Cluster.Do method checks the keys of the given Action / Pipeline and returns an error if any two keys are not in the same slot.

**Comment by varknull** [comment]
Thanks for the clarification. Cheers!
