### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by thuroc** [mediocregopher/radix.v3#5]
go get github.com/mediocregopher/radix.v3
# github.com/mediocregopher/radix.v3/resp
src/github.com/mediocregopher/radix.v3/resp/resp.go:749: reader.Reset undefined (type *bytes.Reader has no field or method Reset)

sync.Pool has no Reset method...

**Comment by mediocregopher** [comment]
Hi @thuroc! Can you check what version of go you have? `*bytes.Reader` surely does have a Reset method:

https://golang.org/pkg/bytes/#Reader.Reset

But possibly that's a more recent addition

**Comment by thuroc** [comment]
Hi @mediocregopher 

yes, that's right. My Version was too old (1.6.4).

After an update to the current go version 1.9.2 all works fine.

Thank you very much.
