### ISSUE TITLE
pingSpin 

### ISSUE THREAD

**Issue by IIInsomnia** [mediocregopher/radix.v3#6]
```go
t := time.NewTicker(10 * time.Second / time.Duration(cap(sp.pool)))
```

If the number of conns is too many, the `PING` is too frequent.

**Comment by mediocregopher** [comment]
How many Conns are you working with? And how are you determining it's too many? Are the number of pings affecting the redis server in some way?

**Comment by mediocregopher** [comment]
I'm gonna go ahead and close this, my latest commit allows for specifying the ping interval, so you can set it to whatever you're comfortable with, or turn it off all-together
