### ISSUE TITLE
PubSub pattern matching only works with *

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix.v3#8]
`PSUBSCRIBE` [supports 3 glob style patterns](https://redis.io/commands/psubscribe) but the package currently [only handles `*` wildcards](https://github.com/mediocregopher/radix.v3/blob/9f9e105/glob.go#L32).

There is really no need to do custom pattern matching since Redis already returns the matched pattern for messages and will return a message multiple times when it matches multiple subscribed patterns. The [PubSubConn](https://godoc.org/github.com/mediocregopher/radix.v3#PubSubConn) already keeps subscribtions by pattern so it could just do a simple map lookup instead of trying to match all known patterns.

This is even [noted in the Pub/Sub docs](https://redis.io/topics/pubsub#client-library-implementation-hints).

**Comment by nussjustin** [comment]
I have [a fix ready](https://github.com/mediocregopher/radix.v3/compare/master...nussjustin:no-glob?expand=1) that I can submit if this gets accepted.

**Comment by mediocregopher** [comment]
You're totally write, I dunno what I was thinking to go through all that effort with the glob matching >_< please do submit that fix, that'd be awesome. Thank you!

**Comment by nussjustin** [comment]
Yeah. I only noticed after trying to refactor and optimize the glob matching and than, after realizing the other placeholders were not supported, half an hour trying to support matching of ? And [] via regexp :-D
